include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    # Error rules
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    # Formatting rules
    curly_braces_in_flow_control_structures: true
    # Documentation rules
    package_api_docs: true
    public_member_api_docs: false  # Turned off to simplify development 